package fr.formation.inti.entity;
// Generated 11 janv. 2023 � 12:23:29 by Hibernate Tools 5.1.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "bd_example2")
public class Employee implements java.io.Serializable {

	private Integer empId;
	private String FIRST_NAME;
	private String LAST_NAME;
	private Date START_DATE;
	private String title;

	public Employee() {
	}

	public Employee(String FIRST_NAME, String LAST_NAME, Date START_DATE) {
		this.FIRST_NAME = FIRST_NAME;
		this.LAST_NAME = LAST_NAME;
		this.START_DATE = START_DATE;
	}

	public Employee(String FIRST_NAME,String LAST_NAME, Date START_DATE, String title) {
	
		this.FIRST_NAME = FIRST_NAME;
		this.LAST_NAME = LAST_NAME;
		this.START_DATE = START_DATE;
		this.title = title;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMP_ID", unique = true, nullable = false)
	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}


	@Column(name = "FIRST_NAME", nullable = false, length = 20)
	public String getFirstName() {
		return this.FIRST_NAME;
	}

	public void setFirstName(String FIRST_NAME) {
		this.FIRST_NAME = FIRST_NAME;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 20)
	public String getLastName() {
		return this.LAST_NAME;
	}

	public void setLastName(String LAST_NAME) {
		this.LAST_NAME = LAST_NAME;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.START_DATE;
	}

	public void setStartDate(Date START_DATE) {
		this.START_DATE = START_DATE;
	}

	@Column(name = "TITLE", length = 20)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
